# Generated by Django 5.2.6 on 2025-10-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_abacatepay_customer_id_user_gateway_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_active_subscription',
            field=models.BooleanField(default=False, verbose_name='Possui Assinatura Ativa?'),
        ),
    ]
