# Generated by Django 5.2.7 on 2025-10-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_has_active_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='taxId',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
    ]
