# Generated by Django 5.2.6 on 2025-10-10 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedGif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(verbose_name='Descrição (Prompt)')),
                ('overlay_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto Sobreposto')),
                ('gif_url', models.URLField(max_length=500, verbose_name='URL do GIF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GIF Gerado',
                'verbose_name_plural': 'GIFs Gerados',
                'ordering': ['-created_at'],
            },
        ),
    ]
