# Generated by Django 5.2.6 on 2025-09-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='frequency',
            field=models.CharField(choices=[('MULTIPLE_PAYMENTS', 'Assinatura'), ('ONE_TIME', 'Pagamento Único')], max_length=20),
        ),
    ]
