# Generated by Django 5.2.6 on 2025-09-28 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_plan_frequency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='abacatepay_billing_id',
            new_name='gateway_subscription_id',
        ),
    ]
