# Generated by Django 5.2.6 on 2025-09-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_rename_abacatepay_billing_id_subscription_gateway_subscription_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='frequency',
        ),
        migrations.AddField(
            model_name='plan',
            name='cycle',
            field=models.CharField(choices=[('MONTHLY', 'Mensal'), ('YEARLY', 'Anual')], default='MONTHLY', max_length=20),
        ),
    ]
