# Generated by Django 5.2.6 on 2025-10-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_plan_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='asaas_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
