# Generated by Django 5.2.6 on 2025-10-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_subscription_asaas_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='cancellation_requested',
            field=models.BooleanField(default=False),
        ),
    ]
