# Generated by Django 5.2.6 on 2025-10-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_subscription_cancellation_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='next_billing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
