# Generated by Django 5.2.6 on 2025-10-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_subscription_next_billing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='gif_limit',
            field=models.IntegerField(default=30, help_text='Número de GIFs que o usuário pode gerar por mês neste plano.'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='gif_count',
            field=models.IntegerField(default=0, help_text='Número de GIFs gerados no ciclo de faturamento atual.'),
        ),
    ]
