# Generated by Django 5.2.7 on 2025-10-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_plan_gif_limit_subscription_gif_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='gateway_subscription_id',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='asaas_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
